<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="abhishekrb" failures="1" tests="5" name="test_NG.test_NG.NewTest" time="0.093" errors="0" timestamp="2023-08-26T14:04:28 IST" skipped="2">
  <testcase classname="test_NG.test_NG.NewTest" name="Mymethod5" time="0.074">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at test_NG.test_NG.NewTest.Mymethod5(NewTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[Mymethod5 is running ....]]>
    </system-out>
  </testcase> <!-- Mymethod5 -->
  <testcase classname="test_NG.test_NG.NewTest" name="Mymethod4" time="0.001">
    <skipped/>
  </testcase> <!-- Mymethod4 -->
  <testcase classname="test_NG.test_NG.NewTest" name="Mymethod3" time="0.001">
    <skipped/>
  </testcase> <!-- Mymethod3 -->
  <testcase classname="test_NG.test_NG.NewTest" name="Mymethod2" time="0.009">
    <system-out>
      <![CDATA[Mymethod2 is running ....]]>
    </system-out>
  </testcase> <!-- Mymethod2 -->
  <testcase classname="test_NG.test_NG.NewTest" name="Mymethod1" time="0.008">
    <system-out>
      <![CDATA[Mymethod1 is running ....]]>
    </system-out>
  </testcase> <!-- Mymethod1 -->
  <system-out>
    <![CDATA[Mymethod5 is running ....
Mymethod2 is running ....
Mymethod1 is running ....]]>
  </system-out>
</testsuite> <!-- test_NG.test_NG.NewTest -->
